---
apiVersion: v1
kind: Service
metadata:
  name: {{★include★"librespeed.fullname"★.★: null}: null}
  labels: {{-★include★"librespeed.labels"★.★|★nindent★4★: null}: null}
spec:
  type: {{★.Values.service.type★: null}: null}
  ports:
    - port: {{★.Values.service.port★: null}: null}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{-★include★"librespeed.selectorLabels"★.★|★nindent★4★: null}: null}
