---
apiVersion: v2
name: transmission-openvpn
version: 1.0.0
kubeVersion: '>=1.22.0-0'
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.4.0
