---
controllers:
  main:
    pod:
      securityGroup:
      fsGroup: 1000
    containers:
      main:
        image:
          repository: haugene/transmission-openvpn
          tag: 5.3.0
        env:
          - name: PUID
            value: 1000
          - name: PGID
            value: 1000
          - name: LOCAL_NETWORK
            value: 10.0.0.0/8
          - name: TRANSMISSION_DOWNLOAD_DIR
            value: /data/transmission/completed
          - name: TRANSMISSION_INCOMPLETE_DIR
            value: /data/transmission/incomplete
          - name: OPENVPN_PROVIDER
            value: NORDVPN
          - name: NORDVPN_COUNTRY
            value: US
          - name: NORDVPN_CATEGORY
            value: legacy_p2p
        envFrom:
          - secretRef:
              name: openvpn
        securityContext:
          capabilities:
            add: [NET_ADMIN]
service:
  main:
    controller: main
    ports:
      http:
        port: 9091
ingress:
  main:
    className: traefik
    hosts:
      - host: tm.jahn16.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
persistence:
  config:
    enabled: true
    type: emptyDir
  data:
    enabled: true
    existingClaim: media
    globalMounts:
      - path: /data/transmission
        subPath: data/transmission/
