controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          repository: lldap/lldap
          tag: v0.5.0
        env:
          - name: LLDAP_BASE_DN
            value: dc=jahn16,dc=com
          - name: LLDAP_LDAP_USER_PASS
            valueFrom:
              secretKeyRef:
                name: ldap
                key: LDAP_PASSWORD
          - name: LLDAP_JTW_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: password
service:
  main:
    controller: main
    ports:
      ldap:
        protocol: TCP
        port: 3890
      http:
        port: 17170

ingress:
  main:
    hosts:
      - host: lldap.jahn16.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
