apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
