---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: postgres
  data:
    - secretKey: username
      remoteRef:
        key: DB_USERNAME
    - secretKey: password
      remoteRef:
        key: DB_PASSWORD
