---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-key
  namespace: authentik
spec:
  target:
    name: secret-key
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: secret-key
