---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: universal-auth-credentials
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: universal-auth-credentials
            namespace: external-secrets
      secretsScope:
        projectSlug: kubernetes-zc-oi
        environmentSlug: dev
        secretsPath: /
