---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: digitalocean-dns
  data:
    - secretKey: access-token
      remoteRef:
        key: DIGITAL_OCEAN_ACCESS_TOKEN
