---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ldap
  data:
  dataFrom:
    - find:
        path: LDAP_
