---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: lldap
spec:
  target:
    name: jwt-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password
