apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openvpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: openvpn

  data:
  dataFrom:
    - find:
        path: OPENVPN_

