apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: postgresql

  data:
  dataFrom:
    - find:
        path: DB_
