---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich
spec:
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: /srv/immich
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [vps.jahn16.com]
