---
controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 1.24.1-nightly
        env:
          - name: PUID
            value: 1000
          - name: PGID
            value: 1000
          - name: TZ
            value: Etc/UTC
service:
  main:
    controller: main
    ports:
      http:
        port: 9696
ingress:
  main:
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: media-authentik@kubernetescrd
    hosts:
      - host: pw.jahn16.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
persistence:
  config:
    existingClaim: servarr
    globalMounts:
      - path: /config
        subPath: prowlarr
